name: bimba_site
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - matplotlib
  - pyyaml
  - trimesh
  - python-graphviz
  - pip
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1

  - pip:
      - causal-conv1d==1.0.0
      - mamba-ssm==1.0.1
      - einops
      - timm==0.4.12
      - biopython
      - meshio
      - pdb2sql
